# Generated by Django 2.0.6 on 2018-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_aluno_disciplina_disciplinaofertada'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='senha',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
